[package]
name = "regex_proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
patterns = { path = "../patterns"}
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

