macro_rules! ascii {
    // most-general tokens first
    (_) => { ANY };
    (e) => { 101 | ALPHA };
    (s) => { 115 | ALPHA };
    (i) => { 105 | ALPHA };
    (a) => { 97 | ALPHA };
    (r) => { 114 | ALPHA };
    (n) => { 110 | ALPHA };
    (t) => { 116 | ALPHA };
    (o) => { 111 | ALPHA };
    (l) => { 108 | ALPHA };
    (c) => { 99 | ALPHA };
    (d) => { 100 | ALPHA };
    (u) => { 117 | ALPHA };
    (g) => { 103 | ALPHA };
    (p) => { 112 | ALPHA };
    (m) => { 109 | ALPHA };
    (h) => { 104 | ALPHA };
    (b) => { 98 | ALPHA };
    (y) => { 121 | ALPHA };
    (f) => { 102 | ALPHA };
    (v) => { 118 | ALPHA };
    (k) => { 107 | ALPHA };
    (w) => { 119 | ALPHA };
    (z) => { 122 | ALPHA };
    (x) => { 120 | ALPHA };
    (j) => { 106 | ALPHA };
    (q) => { 113 | ALPHA };

    (A) => { 65 | ALPHA };
    (B) => { 66 | ALPHA };
    (C) => { 67 | ALPHA };
    (D) => { 68 | ALPHA };
    (E) => { 69 | ALPHA };
    (F) => { 70 | ALPHA };
    (G) => { 71 | ALPHA };
    (H) => { 72 | ALPHA };
    (I) => { 73 | ALPHA };
    (J) => { 74 | ALPHA };
    (K) => { 75 | ALPHA };
    (L) => { 76 | ALPHA };
    (M) => { 77 | ALPHA };
    (N) => { 78 | ALPHA };
    (O) => { 79 | ALPHA };
    (P) => { 80 | ALPHA };
    (Q) => { 81 | ALPHA };
    (R) => { 82 | ALPHA };
    (S) => { 83 | ALPHA };
    (T) => { 84 | ALPHA };
    (U) => { 85 | ALPHA };
    (V) => { 86 | ALPHA };
    (W) => { 87 | ALPHA };
    (X) => { 88 | ALPHA };
    (Y) => { 89 | ALPHA };
    (Z) => { 90 | ALPHA };

    // panic
    ($any:literal) => { test!($any) };
    ($any:tt) => { panic!("illegal non-ascii token {}", $any) }

}

macro_rules! literal_to_ident {
    ('d') => { e_d };
    ('w') => { e_w  };
    ('t') => { e_t };
    ('n') => { n_ };
    ('s') => { WHITESPACE };
    ('S') => { NON_WHITESPACE };
    ('!') => { 33 | UNCLASSIFIED };
    ('"') => { 34 | UNCLASSIFIED };
    ('#') => { 35 | UNCLASSIFIED };
    ('$') => { 36 | UNCLASSIFIED };
    ('%') => { 37 | UNCLASSIFIED };
    ('&') => { 38 | UNCLASSIFIED };
    ('\'') => { 39 | UNCLASSIFIED };
    ('*') => { 42 | UNCLASSIFIED };
    ('+') => { 43 | UNCLASSIFIED };
    (',') => { 44 | UNCLASSIFIED };
    ('-') => { 45 | UNCLASSIFIED };
    ('.') => { 46 | UNCLASSIFIED };
    ('/') => { 47 | UNCLASSIFIED };
    (':') => { 58 | UNCLASSIFIED };
    (';') => { 59 | UNCLASSIFIED };
    ('<') => { 60 | UNCLASSIFIED };
    ('=') => { 61 | UNCLASSIFIED };
    ('>') => { 62 | UNCLASSIFIED };
    ('[') => { 123 | UNCLASSIFIED };
    (']') => { 125 | UNCLASSIFIED };
    ('{') => { 91 | UNCLASSIFIED };
    ('}') => { 93 | UNCLASSIFIED };
    ('(') => { 40 | UNCLASSIFIED };
    (')') => { 41 | UNCLASSIFIED };
    (' ') => { 32 | WHITESPACE };
    ('?') => { 63 | UNCLASSIFIED };
    ('@') => { 64 | UNCLASSIFIED };
    ('\\') => { 92 | UNCLASSIFIED };
    ('^') => { 94 | UNCLASSIFIED };
    ('`') => { 96 | UNCLASSIFIED };
    ('|') => { 124 | UNCLASSIFIED };
    ('~') => { 126 | UNCLASSIFIED };
    // exact alphanumeric characters arent used too much when lexing code
    // Pretty much just keywords
    // We order these based on dictionary frequency for a little extra performance
    ('_') => { 95 | ALPHA };
    // unnecessarily-escaped characters
    ('e') => { 101 | ALPHA };
    ('s') => { 115 | ALPHA };
    ('i') => { 105 | ALPHA };
    ('a') => { 97 | ALPHA };
    ('r') => { 114 | ALPHA };
    ('n') => { 110 | ALPHA };
    ('t') => { 116 | ALPHA };
    ('o') => { 111 | ALPHA };
    ('l') => { 108 | ALPHA };
    ('c') => { 99 | ALPHA };
    ('d') => { 100 | ALPHA };
    ('u') => { 117 | ALPHA };
    ('g') => { 103 | ALPHA };
    ('p') => { 112 | ALPHA };
    ('m') => { 109 | ALPHA };
    ('h') => { 104 | ALPHA };
    ('b') => { 98 | ALPHA };
    ('y') => { 121 | ALPHA };
    ('f') => { 102 | ALPHA };
    ('v') => { 118 | ALPHA };
    ('k') => { 107 | ALPHA };
    ('w') => { 119 | ALPHA };
    ('z') => { 122 | ALPHA };
    ('x') => { 120 | ALPHA };
    ('j') => { 106 | ALPHA };
    ('q') => { 113 | ALPHA };

    ('A') => { 65 | ALPHA };
    ('B') => { 66 | ALPHA };
    ('C') => { 67 | ALPHA };
    ('D') => { 68 | ALPHA };
    ('E') => { 69 | ALPHA };
    ('F') => { 70 | ALPHA };
    ('G') => { 71 | ALPHA };
    ('H') => { 72 | ALPHA };
    ('I') => { 73 | ALPHA };
    ('J') => { 74 | ALPHA };
    ('K') => { 75 | ALPHA };
    ('L') => { 76 | ALPHA };
    ('M') => { 77 | ALPHA };
    ('N') => { 78 | ALPHA };
    ('O') => { 79 | ALPHA };
    ('P') => { 80 | ALPHA };
    ('Q') => { 81 | ALPHA };
    ('R') => { 82 | ALPHA };
    ('S') => { 83 | ALPHA };
    ('T') => { 84 | ALPHA };
    ('U') => { 85 | ALPHA };
    ('V') => { 86 | ALPHA };
    ('W') => { 87 | ALPHA };
    ('X') => { 88 | ALPHA };
    ('Y') => { 89 | ALPHA };
    ('Z') => { 90 | ALPHA };
    ('0') => { 48 | DIGIT };
    ('1') => { 49 | DIGIT };
    ('2') => { 50 | DIGIT };
    ('3') => { 51 | DIGIT };
    ('4') => { 52 | DIGIT };
    ('5') => { 53 | DIGIT };
    ('6') => { 54 | DIGIT };
    ('7') => { 55 | DIGIT };
    ('8') => { 56 | DIGIT };
    ('9') => { 57 | DIGIT };

    (0) => { 48 | DIGIT };
    (1) => { 49 | DIGIT };
    (2) => { 50 | DIGIT };
    (3) => { 51 | DIGIT };
    (4) => { 52 | DIGIT };
    (5) => { 53 | DIGIT };
    (6) => { 54 | DIGIT };
    (7) => { 55 | DIGIT };
    (8) => { 56 | DIGIT };
    (9) => { 57 | DIGIT };
}

macro_rules! ascii_l {
    ('d') => { 254 | DIGIT };
    ('w') => { 253 | ALPHA_NUMERIC  };
    ('t') => { 9 | WHITESPACE };
    ('n') => { 10 | WHITESPACE };
    ('s') => { WHITESPACE };
    ('S') => { NON_WHITESPACE };
    ('!') => { 33 | UNCLASSIFIED };
    ('"') => { 34 | UNCLASSIFIED };
    ('#') => { 35 | UNCLASSIFIED };
    ('$') => { 36 | UNCLASSIFIED };
    ('%') => { 37 | UNCLASSIFIED };
    ('&') => { 38 | UNCLASSIFIED };
    ('\'') => { 39 | UNCLASSIFIED };
    ('*') => { 42 | UNCLASSIFIED };
    ('+') => { 43 | UNCLASSIFIED };
    (',') => { 44 | UNCLASSIFIED };
    ('-') => { 45 | UNCLASSIFIED };
    ('.') => { 46 | UNCLASSIFIED };
    ('/') => { 47 | UNCLASSIFIED };
    (':') => { 58 | UNCLASSIFIED };
    (';') => { 59 | UNCLASSIFIED };
    ('<') => { 60 | UNCLASSIFIED };
    ('=') => { 61 | UNCLASSIFIED };
    ('>') => { 62 | UNCLASSIFIED };
    ('[') => { 123 | UNCLASSIFIED };
    (']') => { 125 | UNCLASSIFIED };
    ('{') => { 91 | UNCLASSIFIED };
    ('}') => { 93 | UNCLASSIFIED };
    ('(') => { 40 | UNCLASSIFIED };
    (')') => { 41 | UNCLASSIFIED };
    (' ') => { 32 | WHITESPACE };
    ('?') => { 63 | UNCLASSIFIED };
    ('@') => { 64 | UNCLASSIFIED };
    ('\\') => { 92 | UNCLASSIFIED };
    ('^') => { 94 | UNCLASSIFIED };
    ('`') => { 96 | UNCLASSIFIED };
    ('|') => { 124 | UNCLASSIFIED };
    ('~') => { 126 | UNCLASSIFIED };
    // exact alphanumeric characters arent used too much when lexing code
    // Pretty much just keywords
    // We order these based on dictionary frequency for a little extra performance
    ('_') => { 95 | ALPHA };
    // unnecessarily-escaped characters
    ('e') => { 101 | ALPHA };
    ('s') => { 115 | ALPHA };
    ('i') => { 105 | ALPHA };
    ('a') => { 97 | ALPHA };
    ('r') => { 114 | ALPHA };
    ('n') => { 110 | ALPHA };
    ('t') => { 116 | ALPHA };
    ('o') => { 111 | ALPHA };
    ('l') => { 108 | ALPHA };
    ('c') => { 99 | ALPHA };
    ('d') => { 100 | ALPHA };
    ('u') => { 117 | ALPHA };
    ('g') => { 103 | ALPHA };
    ('p') => { 112 | ALPHA };
    ('m') => { 109 | ALPHA };
    ('h') => { 104 | ALPHA };
    ('b') => { 98 | ALPHA };
    ('y') => { 121 | ALPHA };
    ('f') => { 102 | ALPHA };
    ('v') => { 118 | ALPHA };
    ('k') => { 107 | ALPHA };
    ('w') => { 119 | ALPHA };
    ('z') => { 122 | ALPHA };
    ('x') => { 120 | ALPHA };
    ('j') => { 106 | ALPHA };
    ('q') => { 113 | ALPHA };

    ('A') => { 65 | ALPHA };
    ('B') => { 66 | ALPHA };
    ('C') => { 67 | ALPHA };
    ('D') => { 68 | ALPHA };
    ('E') => { 69 | ALPHA };
    ('F') => { 70 | ALPHA };
    ('G') => { 71 | ALPHA };
    ('H') => { 72 | ALPHA };
    ('I') => { 73 | ALPHA };
    ('J') => { 74 | ALPHA };
    ('K') => { 75 | ALPHA };
    ('L') => { 76 | ALPHA };
    ('M') => { 77 | ALPHA };
    ('N') => { 78 | ALPHA };
    ('O') => { 79 | ALPHA };
    ('P') => { 80 | ALPHA };
    ('Q') => { 81 | ALPHA };
    ('R') => { 82 | ALPHA };
    ('S') => { 83 | ALPHA };
    ('T') => { 84 | ALPHA };
    ('U') => { 85 | ALPHA };
    ('V') => { 86 | ALPHA };
    ('W') => { 87 | ALPHA };
    ('X') => { 88 | ALPHA };
    ('Y') => { 89 | ALPHA };
    ('Z') => { 90 | ALPHA };
    ('0') => { 48 | DIGIT };
    ('1') => { 49 | DIGIT };
    ('2') => { 50 | DIGIT };
    ('3') => { 51 | DIGIT };
    ('4') => { 52 | DIGIT };
    ('5') => { 53 | DIGIT };
    ('6') => { 54 | DIGIT };
    ('7') => { 55 | DIGIT };
    ('8') => { 56 | DIGIT };
    ('9') => { 57 | DIGIT };

    (0) => { 48 | DIGIT };
    (1) => { 49 | DIGIT };
    (2) => { 50 | DIGIT };
    (3) => { 51 | DIGIT };
    (4) => { 52 | DIGIT };
    (5) => { 53 | DIGIT };
    (6) => { 54 | DIGIT };
    (7) => { 55 | DIGIT };
    (8) => { 56 | DIGIT };
    (9) => { 57 | DIGIT };
}

pub(crate) use ascii;
pub(crate) use ascii_l;